server:
   port: 8021
spring:
   application:
      name: microservice-consumer-movie-feign-with-hystrix
eureka:
   client:
      serviceUrl:
         defaultZone: http://localhost:8761/eureka/
   instance:
      preferIpAddress: true
feign:
   hystrix:
      enabled: true
# 设置hystrix超时时间 (解决Feign hystrix 首次失败问题)
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 5000
## 禁用hystrix超时时间: (解决Feign hystrix 首次失败问题)
#hystrix:
#  command:
#    default:
#      execution:
#        timeout:
#          enabled: false






